INSERT INTO "Symptoms" (name, "createdAt", "updatedAt") VALUES 
('Headache', NOW(), NOW()),
('Lightheadedness', NOW(), NOW()),
('Watery eyes', NOW(), NOW()),
('Itchy eyes', NOW(), NOW()),
('Runny nose', NOW(), NOW()),
('Itchy nose', NOW(), NOW()),
('Sneezing', NOW(), NOW()),
('Tongue swelling', NOW(), NOW()),
('Sore throat', NOW(), NOW()),
('Throat tightness', NOW(), NOW()),
('Coughing', NOW(), NOW()),
('Wheezing', NOW(), NOW()),
('Chest tightness', NOW(), NOW()),
('Shortness of breath', NOW(), NOW()),
('Nausea', NOW(), NOW()),
('Vomiting', NOW(), NOW()),
('Stomach cramps', NOW(), NOW()),
('Diarrhea', NOW(), NOW()),
('Fever', NOW(), NOW()),
('Fatigue', NOW(), NOW()),
('Body aches', NOW(), NOW()),
('Rash', NOW(), NOW()),
('Hives', NOW(), NOW()); 